// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens(token, created_at, updated_at, user_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type CreateRefreshTokenParams struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefreshToken,
		arg.Token,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserFromRefreshToken = `-- name: GetUserFromRefreshToken :one
SELECT user_id, revoked_at
FROM refresh_tokens
WHERE token = $1
`

type GetUserFromRefreshTokenRow struct {
	UserID    uuid.UUID
	RevokedAt sql.NullTime
}

func (q *Queries) GetUserFromRefreshToken(ctx context.Context, token string) (GetUserFromRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserFromRefreshToken, token)
	var i GetUserFromRefreshTokenRow
	err := row.Scan(&i.UserID, &i.RevokedAt)
	return i, err
}

const revokeTokenByToken = `-- name: RevokeTokenByToken :exec
UPDATE refresh_tokens
SET updated_at = $1, revoked_at = $1
WHERE token = $2
`

type RevokeTokenByTokenParams struct {
	UpdatedAt time.Time
	Token     string
}

func (q *Queries) RevokeTokenByToken(ctx context.Context, arg RevokeTokenByTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeTokenByToken, arg.UpdatedAt, arg.Token)
	return err
}

const revokeTokensByUser = `-- name: RevokeTokensByUser :exec
UPDATE refresh_tokens
SET updated_at = $1, revoked_at = $1
WHERE user_id = $2
`

type RevokeTokensByUserParams struct {
	UpdatedAt time.Time
	UserID    uuid.UUID
}

func (q *Queries) RevokeTokensByUser(ctx context.Context, arg RevokeTokensByUserParams) error {
	_, err := q.db.ExecContext(ctx, revokeTokensByUser, arg.UpdatedAt, arg.UserID)
	return err
}
